import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import type { JanitorResult, JanitorOptions } from "./types.js";
import { logger } from "./logger.js";

export function buildIssuePayload(
  result: JanitorResult,
  repo: string,
  branch: string,
  commitSha: string,
): { title: string; body: string; labels: string[] } {
  const drift = result.report.findings;
  const grouped = new Map<string, typeof drift>();
  for (const f of drift) {
    const key = f.kind;
    const list = grouped.get(key) ?? [];
    grouped.set(key, [...list, f]);
  }
  const sections: string[] = [];
  sections.push(
    `### Auto-generated by \`entropy-janitors/${result.report.kind}\``,
  );
  sections.push(`- **Repository:** ${repo}`);
  sections.push(`- **Branch:** \`${branch}\` @ \`${commitSha.slice(0, 7)}\``);
  sections.push(`- **Generated:** ${result.report.generatedAt}`);
  sections.push(`- **Scanned:** ${result.report.summary.scanned}`);
  sections.push(`- **Findings:** ${result.report.summary.findings}`);
  sections.push(`- **Duration:** ${result.report.summary.durationMs} ms`);
  sections.push("");
  sections.push("## Findings by kind");
  for (const [kind, items] of grouped) {
    sections.push(`### \`${kind}\` (${items.length})`);
    for (const f of items.slice(0, 50)) {
      const loc = f.line !== undefined ? `${f.path}:${f.line}` : f.path;
      sections.push(`- **${f.severity}** \`${loc}\` — ${f.message}`);
    }
    if (items.length > 50) {
      sections.push(`- _…and ${items.length - 50} more (see attached report)_`);
    }
    sections.push("");
  }
  sections.push("---");
  sections.push(
    "> This issue is auto-generated by the `Entropy Janitors` weekly workflow.",
  );
  sections.push(
    "> Apply lifecycle-marker guards from `sergeant-tech-debt` skill before deleting code.",
  );
  return {
    title: result.issueTitle,
    body: sections.join("\n"),
    labels: [...result.issueLabels] as string[],
  };
}

export async function writeReportArtifacts(
  result: JanitorResult,
  options: JanitorOptions,
): Promise<{ reportPath: string; jsonPath: string }> {
  if (!options.outDir) {
    throw new Error("writeReportArtifacts: outDir is required");
  }
  const outDir = resolve(options.root, options.outDir, result.report.kind);
  await mkdir(outDir, { recursive: true });
  const drift = result.report.findings;
  const grouped = new Map<string, typeof drift>();
  for (const f of drift) {
    const list = grouped.get(f.kind) ?? [];
    grouped.set(f.kind, [...list, f]);
  }
  const lines: string[] = [];
  lines.push(`# Entropy Janitor Report — ${result.report.kind}`);
  lines.push("");
  lines.push(`Generated: ${result.report.generatedAt}`);
  lines.push(`Scanned: ${result.report.summary.scanned} items`);
  lines.push(`Findings: ${result.report.summary.findings}`);
  lines.push(`Duration: ${result.report.summary.durationMs} ms`);
  lines.push("");
  for (const [kind, items] of grouped) {
    lines.push(`## ${kind} (${items.length})`);
    lines.push("");
    for (const f of items) {
      const loc = f.line !== undefined ? `${f.path}:${f.line}` : f.path;
      lines.push(`- **[${f.severity}]** \`${loc}\` — ${f.message}`);
    }
    lines.push("");
  }
  const reportPath = resolve(outDir, "report.md");
  const jsonPath = resolve(outDir, "report.json");
  await mkdir(dirname(reportPath), { recursive: true });
  await writeFile(reportPath, lines.join("\n"), "utf8");
  await writeFile(jsonPath, JSON.stringify(result.report, null, 2), "utf8");
  logger.info("report written", { reportPath, findings: drift.length });
  return { reportPath, jsonPath };
}

export function printCliSummary(
  result: JanitorResult,
  options: JanitorOptions,
): void {
  const driftCount = result.report.findings.length;
  if (options.json) {
    process.stdout.write(JSON.stringify(result, null, 2) + "\n");
    return;
  }
  const lines: string[] = [];
  lines.push(
    `[${result.report.kind}] scanned=${result.report.summary.scanned} findings=${driftCount} durationMs=${result.report.summary.durationMs}`,
  );
  for (const f of result.report.findings.slice(0, 20)) {
    const loc = f.line !== undefined ? `${f.path}:${f.line}` : f.path;
    lines.push(`  - [${f.severity}] ${f.kind} ${loc} — ${f.message}`);
  }
  if (driftCount > 20) lines.push(`  - …and ${driftCount - 20} more`);
  process.stdout.write(lines.join("\n") + "\n");
}
