-- 030: openclaw_write_audit — DB-persistent audit-trail for OpenClaw
-- write-tool approve / executed / reject transitions.
--
-- Phase 4.5 (ADR-0037). Closes the residual debt from ADR-0036 §4 ("Phase
-- 4.5 wires this signal into a DB-table"). Until now, every approve /
-- reject / executed transition was a single `console.log("[openclaw]
-- write-tool …", { … })` in `tools/openclaw`. Railway log retention drops
-- old lines and `grep` is the only "query"; this migration replaces that
-- with a queryable append-only log.
--
-- One row per lifecycle transition (NOT one row per approval-id):
--
--   * `approved` — founder clicked Approve, BEFORE the upstream HTTP call.
--   * `executed` — same approval_id, AFTER the HTTP call (with
--                   http_status + ok + response_excerpt).
--   * `rejected` — founder clicked Reject. Single row, no `executed` follow-up.
--
-- Pairing `approved` + `executed` per `approval_id` reconstructs the
-- end-to-end timing ("approve-to-executed latency") and exposes failure
-- modes ("approved but never executed → executor crashed mid-flight").
--
-- Forward-additive: existing apps keep working — read-paths to this table
-- are new (write-audit/list endpoint + /audit slash command). The console
-- only writes through fail-soft `void postJson(…)`, so audit-endpoint
-- outages never block the user-visible Approve/Reject feedback.

CREATE TABLE IF NOT EXISTS openclaw_write_audit (
  id                 BIGSERIAL PRIMARY KEY,
  recorded_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- 8-char hex generated by `tools/openclaw/src/openclaw/approval-store.ts`.
  -- Same id appears in 'approved' AND 'executed' rows when the founder
  -- approved + we then ran the HTTP call (rejected → just the one row).
  approval_id        TEXT NOT NULL,

  -- One of OPENCLAW_WRITE_TOOL_NAMES (commit_to_strategy_doc,
  -- create_github_issue, post_to_topic, pause_workflow, mute_alert).
  -- Soft-validated as TEXT here so future Phase 4.x additions don't
  -- require a CHECK-constraint redeploy.
  tool               TEXT NOT NULL,

  -- Better Auth user.id of founder (TEXT). Matches openclaw_invocations
  -- contract.
  founder_user_id    TEXT NOT NULL,

  -- Telegram user-id (BIGINT — over 32-bit per Telegram spec).
  founder_tg_user_id BIGINT NOT NULL,

  -- The invocation row that emitted the original LLM tool-call. Nullable
  -- so future GC of openclaw_invocations doesn't cascade-delete the
  -- audit-log; ON DELETE SET NULL keeps the audit-log alive on its own.
  invocation_id      BIGINT REFERENCES openclaw_invocations(id) ON DELETE SET NULL,

  -- Lifecycle action; CHECK enforced because the contract is fixed
  -- (handler emits exactly these three).
  action             TEXT NOT NULL
    CHECK (action IN ('approved','executed','rejected')),

  -- Snapshot of write-tool input (from the approval-card payload).
  -- Truncated server-side if needed — JSONB itself isn't size-limited but
  -- console upstream caps at ~80 KB (commit_to_strategy_doc.content).
  input              JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Populated only for action='executed' rows.
  http_status        INTEGER,
  ok                 BOOLEAN,
  response_excerpt   TEXT,

  -- Persona that emitted the tool-call (cofounder | ops | growth | eng |
  -- finance). Nullable for backwards-compat with calls that don't pass it.
  persona            TEXT,

  -- Free-form extras (council step id, retry count, etc.). Mirrors the
  -- pattern used by openclaw_invocations.metadata.
  metadata           JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- Most queries scan recent rows globally — `/audit` slash, post-mortems.
CREATE INDEX IF NOT EXISTS openclaw_write_audit_recorded_idx
  ON openclaw_write_audit (recorded_at DESC);

-- Reconstructing one approval's lifecycle (`approved` then `executed`).
CREATE INDEX IF NOT EXISTS openclaw_write_audit_approval_idx
  ON openclaw_write_audit (approval_id, recorded_at DESC);

-- Filter "all post_to_topic actions in last 30 days".
CREATE INDEX IF NOT EXISTS openclaw_write_audit_tool_idx
  ON openclaw_write_audit (tool, recorded_at DESC);

-- Per-founder timeline (multi-operator-ready in Phase 5).
CREATE INDEX IF NOT EXISTS openclaw_write_audit_founder_idx
  ON openclaw_write_audit (founder_user_id, recorded_at DESC);

COMMENT ON TABLE openclaw_write_audit IS
  'OpenClaw write-tool audit log: one row per approve/reject/executed transition. Append-only. ADR-0037, Phase 4.5.';

COMMENT ON COLUMN openclaw_write_audit.approval_id IS
  '8-char hex from console approval-store. Same id pairs `approved` + `executed` rows.';

COMMENT ON COLUMN openclaw_write_audit.action IS
  'Lifecycle event: approved (pre-HTTP) | executed (post-HTTP) | rejected (terminal).';
