#!/bin/sh
set -e

# Copy config-as-code from the container image to the persistent Gateway workspace volume.
# Runs on every container start — config is code-controlled, not hand-edited on the volume.
# Persistent auth state (Telegram webhook, WhatsApp session) lives on the volume and is NOT
# overwritten here because only the config files (not the workspace/auth subdirs) are copied.

mkdir -p ~/.openclaw/workspace/skills

# Lay down main config (overwrites on each restart).
cp /app/ops/openclaw/openclaw.example.json ~/.openclaw/openclaw.json

# Stage 4b: the plugin now registers 25 read-tools + 5 write-tools
# + 4 lifecycle hooks (`llm_input`, `before_agent_start`, `agent_end`,
# `before_tool_call`) + a Layer 0 shortcut router composed on top of
# `before_agent_start`. The router matches 17 slash-command/Ukrainian
# patterns (e.g. `/metrics`, `дай метрики`), executes the relevant
# read-tools in-process, renders a canned Markdown template, and returns
# `{ block: true, blockReason: "__ROUTED__:" + response }` — LLM cost
# for these turns is $0. If no pattern matches, the router falls
# through to the Stage 4a audit-open hook normally. The Stage 3 contract
# (agent asking in chat first) is no longer required; native approval
# still applies to write-tools via the `before_tool_call` hook.
#
# We restore the persona skills + cheap-router prompt + n8n allowlist from
# the image on every start (config-as-code, never edited on the volume).
#
# Wipe the volume copies first so older content (left over from previous
# image versions or removed skills) doesn't linger, then re-lay-down a
# fresh copy from /app/ops/openclaw/.
rm -rf ~/.openclaw/workspace/skills \
       ~/.openclaw/cheap-router.system.md \
       ~/.openclaw/n8n-allowlist.json
mkdir -p ~/.openclaw/workspace/skills
cp -a /app/ops/openclaw/skills/. ~/.openclaw/workspace/skills/
cp /app/ops/openclaw/cheap-router.system.md ~/.openclaw/cheap-router.system.md
cp /app/ops/openclaw/n8n-allowlist.json ~/.openclaw/n8n-allowlist.json

# Stage-status overlay skill: makes the agent aware that the personas
# above describe the *target* tool-set, and which Stage of the migration
# is live today. As of Stage 4b, the agent also has 17 shortcuts that
# bypass the LLM entirely — these are handled in-process before the
# agent even starts. Native approval still applies to write-tools via
# the `before_tool_call` hook. The agent should still SUMMARISE the
# intended action concisely so the founder can decide quickly when the
# approval prompt arrives.
# OpenClaw reads every SKILL.md under workspace/skills/ as additional
# system context, so adding this file is equivalent to appending a global
# addendum without editing each per-persona file.
mkdir -p ~/.openclaw/workspace/skills/_stage-status
cat > ~/.openclaw/workspace/skills/_stage-status/SKILL.md <<'STAGEEOF'
---
name: _stage-status
description: Sergeant OpenClaw migration stage status. Read this before deciding which tools you actually have.
---

# Stage status (Stage 4b — read-tools + write-tools + 4 hooks + Layer 0 shortcut router live)

> Generated by `ops/openclaw/docker-entrypoint.sh` on every container start.

## Що зараз працює (Stage 4b)

Плагін реєструє **30 tools + 4 hooks + Layer 0 shortcut router (17 shortcuts)** через `api.registerTool` / `api.registerHook`:

**25 read-tools** — безпечні на викид, льотять без підтвердження:

`recall_memory`, `read_strategy_docs`, `record_decision`, `query_app_db`, `get_server_stats`, `get_stripe_metrics`, `get_posthog_stats`, `get_sentry_issues`, `read_github`, `github_search`, `github_tree`, `github_diff`, `github_prs`, `get_github_releases`, `n8n_list`, `n8n_describe`, `n8n_trigger`, `n8n_activate`, `refresh_business_snapshot`, `read_workflow_logs`, `read_telegram_topic`, `seo_gsc_query`, `seo_psi_audit`, `seo_serp_lookup`, `set_reminder`.

**5 write-tools** — мутуючі, гейтяться через `before_tool_call` з native `requireApproval` payload:

`create_github_issue`, `commit_to_strategy_doc`, `post_to_topic`, `pause_workflow`, `mute_alert`.

**4 hooks** (Stage 4a, живі):

- `llm_input` → per-call USD budget gate (`POST /api/internal/openclaw/budget`). Перевіряється ДО кожного LLM-виклику. Якщо бюджет вичерпаний — виклик блокується.
- `before_agent_start` → (Stage 4b) **спершу** перевіряє чи user message підходить под shortcut. Якщо так — викликає tool-и в процесі, рендерить canned template і блокує turn з `__ROUTED__:` prefix-ом (host повинен strip-нути його і показати як assistant turn). Якщо ні — відкриває invocation row (`POST /invocations/open`). Повертає `invocationId`, який корелятор прив'язує до `runId`.
- `agent_end` → фіналізує invocation з cost/duration/status (`POST /invocations/finalize`).
- `before_tool_call` → для write-tools повертає `{ requireApproval: {...} }`. Host сам показує founder-у кнопки allow/deny, результат логується в `/write-audit/log`.

**Layer 0 shortcut router** (Stage 4b, живий) — 17 вхідних патернів, які обробляються БЕЗ LLM-виклику (cost = $0):

`/metrics`, `/runway`, `/status`, `/sentry`, `/stripe`, `/posthog`, `/prs`, `/releases`, `/builds`, `/workflows`, `/refresh_metrics`, `/heartbeat` (або `/health`, `ping`), `/recall <query>`, `/decisions`, `/digest [day|week]`, `/remind <when> <what>`, `/think <question>` — плюс UA-фрази (напр. `дай метрики`, `скільки runway`, `що по sentry`).

Коли user message підходить под shortcut — ти (агент) взагалі НЕ стартуєш, відповідь рендериться в in-process router з fetch-resultів tool-ів без твоєї участі. Це очікувана поведінка. Про виняток `/think <question>` — він **проходить всередину** до тебе як Layer 2 escalation з вимогою розмірковувати як cofounder.

Правило для write-tools (Stage 4a contract — native approval, не в чаті):

1. Коли вирішив викликати write-tool — просто викликай. SDK сам зупинить виконання і попросить founder-а підтвердити.
2. Перед викликом коротко опиши ОДНИМ реченням НАМІР у відповіді («Відкриваю issue «…» у Skords-01/Sergeant») — воно дублюється в approval-UI title і допомагає founder-у вирішити.
3. Якщо founder натиснув deny / timeout / cancel — SDK поверне помилку; роботу продовжуєш без цієї дії або питаєш альтернативний крок.
4. Якщо сервер повертає `not_configured` / `allowlist_fail` — це НЕ баг: поясни founder-у, що відповідна інтеграція ще не налаштована.

## Що ще НЕ працює (Stage 4c+ робота)

- Layer 1 cheap-router (Haiku JSON-класифікатор) — Stage 4c.
- Per-persona tool allowlist (`agents.<id>.tools` у конфігу) — Stage 5a.
- Morning-digest cron через `cron.*` config-block — Stage 5d.

## Поведінка при невідомому tool

Якщо OpenClaw повертає «unknown tool» — **не намагайся уявити результат**. Скажи founder-у точно: «{tool} ще не зареєстрований у поточному build-і, це Stage 4c+ робота».
STAGEEOF

# Plugin bootstrap: @sergeant/openclaw-plugin lives in packages/openclaw-plugin and
# is loaded into the Gateway as an OpenClaw plugin. Install state lives on the
# volume under ~/.openclaw/{plugins,extensions}, so this is real work only on
# first boot (or after a volume reset) and a tolerated no-op on every warm start.
#
# Wipe any prior install state before re-installing: earlier crashed deploys (when
# the manifest still lacked id / dist output / a slim package.json) wrote partial
# entries into installs.json that subsequent --force installs preserved, leaving
# the gateway to validate against stale data and crash on "plugin manifest requires
# id". Clearing the install records + extension dirs is safe — the plugin code
# ships in the image, not on the volume.
rm -rf ~/.openclaw/plugins ~/.openclaw/extensions/sergeant ~/.openclaw/extensions/@sergeant-openclaw-plugin-* || true
openclaw plugins install /app/packages/openclaw-plugin --force || true

# After install, patch in the runtime config block under
# plugins.entries.sergeant.config — kept out of the base config-as-code so the
# gateway doesn't strip it as a stale entry on the validation pass that
# precedes install. The plugin's register() hook reads this block as the
# stringified second argument and would otherwise crash with
# "OpenClaw plugin config is not valid JSON: 'undefined' is not valid JSON".
node /app/ops/openclaw/patch-sergeant-config.mjs

# Hand off to OpenClaw runtime. `gateway run` runs the WebSocket Gateway in the
# foreground (the unqualified `openclaw gateway` would try to install/start a
# systemd unit, which is unavailable in containers — see `openclaw gateway --help`).
# Port 18789 must match the Railway service public-domain target port and the
# HEALTHCHECK in Dockerfile.openclaw-gateway.
exec openclaw gateway run --port 18789
