#!/bin/sh
set -e

# Copy config-as-code from the container image to the persistent Gateway workspace volume.
# Runs on every container start — config is code-controlled, not hand-edited on the volume.
# Persistent auth state (Telegram webhook, WhatsApp session) lives on the volume and is NOT
# overwritten here because only the config files (not the workspace/auth subdirs) are copied.

mkdir -p ~/.openclaw/workspace/skills

# Lay down main config (overwrites on each restart).
cp /app/ops/openclaw/openclaw.example.json ~/.openclaw/openclaw.json

# Stage 3 (PR-C): the plugin now registers 25 read-tools + 5 write-tools
# (matches the persona-skill tool-set, minus hooks which arrive in Stage 4).
# Stage 1 wiped persona skills aggressively because the MVP only had 3
# read-tools and the persona docs claimed a full tool-set, which poisoned
# the agent ("I don't have X"). Stage 2 restored the 25 read-tools and
# Stage 3 closed the write-tool gap; we still need the `_stage-status`
# overlay below so the agent treats write-tools as confirmation-required
# until Stage 4a wires the native approval hook.
#
# We restore the persona skills + cheap-router prompt + n8n allowlist from
# the image on every start (config-as-code, never edited on the volume).
#
# Wipe the volume copies first so older content (left over from previous
# image versions or removed skills) doesn't linger, then re-lay-down a
# fresh copy from /app/ops/openclaw/.
rm -rf ~/.openclaw/workspace/skills \
       ~/.openclaw/cheap-router.system.md \
       ~/.openclaw/n8n-allowlist.json
mkdir -p ~/.openclaw/workspace/skills
cp -a /app/ops/openclaw/skills/. ~/.openclaw/workspace/skills/
cp /app/ops/openclaw/cheap-router.system.md ~/.openclaw/cheap-router.system.md
cp /app/ops/openclaw/n8n-allowlist.json ~/.openclaw/n8n-allowlist.json

# Stage-status overlay skill: makes the agent aware that the personas
# above describe the *target* tool-set, and which Stage of the migration
# is live today. As of Stage 3 (PR-C) all 5 write-tools are registered
# but approval gating is still server-side only — the agent must surface
# any mutating action to the founder for confirmation BEFORE invoking,
# rather than auto-executing.
# OpenClaw reads every SKILL.md under workspace/skills/ as additional
# system context, so adding this file is equivalent to appending a global
# addendum without editing each per-persona file.
mkdir -p ~/.openclaw/workspace/skills/_stage-status
cat > ~/.openclaw/workspace/skills/_stage-status/SKILL.md <<'STAGEEOF'
---
name: _stage-status
description: Sergeant OpenClaw migration stage status. Read this before deciding which tools you actually have.
---

# Stage status (Stage 3 — read-tools + write-tools, no hooks yet)

> Generated by `ops/openclaw/docker-entrypoint.sh` on every container start.

## Що зараз працює (Stage 3)

Плагін реєструє **30 tools** через `api.registerTool`:

**25 read-tools** — безпечні на викид, льотять без підтвердження:

`recall_memory`, `read_strategy_docs`, `record_decision`, `query_app_db`, `get_server_stats`, `get_stripe_metrics`, `get_posthog_stats`, `get_sentry_issues`, `read_github`, `github_search`, `github_tree`, `github_diff`, `github_prs`, `get_github_releases`, `n8n_list`, `n8n_describe`, `n8n_trigger`, `n8n_activate`, `refresh_business_snapshot`, `read_workflow_logs`, `read_telegram_topic`, `seo_gsc_query`, `seo_psi_audit`, `seo_serp_lookup`, `set_reminder`.

**5 write-tools** — мутуючі, потребують **живого підтвердження від founderа в розмові в турні ДО виклику**:

`create_github_issue`, `commit_to_strategy_doc`, `post_to_topic`, `pause_workflow`, `mute_alert`.

Правило для write-tools (Stage 3 contract, Stage 4 додасть automated approval gate):

1. Сформулюй дію розгорнуто: «Я хочу відкрити GitHub issue «Глюк у finyk export» у Skords-01/Sergeant з labels=[bug, p1]».
2. Чекай явного "так/роби" від founder-а. Без дозволу — **не** викликай tool.
3. Після виклику звітуй результат (URL/sha/messageId) АБО помилку.
4. Якщо сервер повертає `not_configured` / `allowlist_fail` — це НЕ баг: поясни founder-у, що відповідна інтеграція ще не налаштована.

## Що ще НЕ працює (Stage 4+ робота)

- Автоматичний approval gate для write-tools (`before_tool_call` hook з `requireApproval` — native SDK mechanism) — Stage 4a.
- Per-call USD budget гейт (`llm_input` hook → `/budget`) — Stage 4a.
- Cheap-router shortcut layer (`before_agent_start` hook) — Stage 4b.
- Per-persona allowlist (`agents.<id>.tools` у конфігу) — Stage 5a.

## Поведінка при невідомому tool

Якщо OpenClaw повертає «unknown tool» — **не намагайся уявити результат**. Скажи founder-у точно: «{tool} ще не зареєстрований у поточному build-і, це Stage 4+ робота».
STAGEEOF

# Plugin bootstrap: @sergeant/openclaw-plugin lives in packages/openclaw-plugin and
# is loaded into the Gateway as an OpenClaw plugin. Install state lives on the
# volume under ~/.openclaw/{plugins,extensions}, so this is real work only on
# first boot (or after a volume reset) and a tolerated no-op on every warm start.
#
# Wipe any prior install state before re-installing: earlier crashed deploys (when
# the manifest still lacked id / dist output / a slim package.json) wrote partial
# entries into installs.json that subsequent --force installs preserved, leaving
# the gateway to validate against stale data and crash on "plugin manifest requires
# id". Clearing the install records + extension dirs is safe — the plugin code
# ships in the image, not on the volume.
rm -rf ~/.openclaw/plugins ~/.openclaw/extensions/sergeant ~/.openclaw/extensions/@sergeant-openclaw-plugin-* || true
openclaw plugins install /app/packages/openclaw-plugin --force || true

# After install, patch in the runtime config block under
# plugins.entries.sergeant.config — kept out of the base config-as-code so the
# gateway doesn't strip it as a stale entry on the validation pass that
# precedes install. The plugin's register() hook reads this block as the
# stringified second argument and would otherwise crash with
# "OpenClaw plugin config is not valid JSON: 'undefined' is not valid JSON".
node /app/ops/openclaw/patch-sergeant-config.mjs

# Hand off to OpenClaw runtime. `gateway run` runs the WebSocket Gateway in the
# foreground (the unqualified `openclaw gateway` would try to install/start a
# systemd unit, which is unavailable in containers — see `openclaw gateway --help`).
# Port 18789 must match the Railway service public-domain target port and the
# HEALTHCHECK in Dockerfile.openclaw-gateway.
exec openclaw gateway run --port 18789
